# Ping to Map: Xaero's edition - Fabric 1.21.4
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.19.3
fabric_version=0.119.4+1.21.4

mod_id=pingtomapxaeros
mod_name=Ping to Map: Xaero's Minimap & Ping Wheel Addon
mod_license=All Rights Reserved
mod_version=1.1.0
mod_group_id=com.kuronami.pingtomapxaeros
mod_authors=KURONAMI
mod_description=Pop a temporary Xaero's Minimap waypoint when a teammate or yourself pings via Ping-Wheel (Fabric 1.21.4).

ping_wheel_version_id=dPn7Pgge
fcap_version=SSKF75hc
xaeros_minimap_version_id=oW2LTmmK
xaeros_worldmap_version_id=9H0p1mmH
