pluginManagement {
    repositories {
        gradlePluginPortal()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = 'https://maven.fabricmc.net/'
                }
            }
            filter {
                includeGroupAndSubgroups('net.fabricmc')
                includeGroup('fabric-loom')
            }
        }
    }
}

rootProject.name = 'ping-to-map-fabric'
